language: python
sudo: required
python:
  - 2.7

jdk:
    - oraclejdk8
#fix to get neo4j working
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - if [[ $SHIPPABLE_JDK_VERSION == "oraclejdk8" ]] ; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; export PATH="$PATH:/usr/lib/jvm/java-8-oracle/bin"; export java_path="/usr/lib/jvm/java-8-oracle/jre/bin/java"; fi
  - echo  $java_path
  - update-alternatives --set java $java_path
  - java -version
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-3.0.1-unix.tar.gz
  - tar -xzf neo4j-community-3.0.1-unix.tar.gz
  - neo4j-community-3.0.1/bin/neo4j start
  - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=neo4jneo4j"


# Install packages
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
