language: python
python:
  - 2.7

#fix to get neo4j working
jdk:
  - oraclejdk8
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-3.0.1-unix.tar.gz
  - tar -xzf neo4j-community-3.0.1-unix.tar.gz
  - neo4j-community-3.0.1/bin/neo4j start
  - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=neo4jneo4j"


# Install packages
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
