language: python
python:
  - 2.7

# Install packages
install:
  - pip install prov requests
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
