language: python
python:
  - 2.7

jdk:
  - oraclejdk8

#set up database
services:
  - neo4j

# Install packages
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
